import { Student, FeePayment, Certificate, GalleryItem, Notice, Inquiry } from "@/types";

export const DEFAULT_STUDENTS: Student[] = [
  {
    id: "stu-1",
    rollNo: "IPS-2026-001",
    name: "Muhammad Hamza Khan",
    email: "hamza.khan@example.com",
    phone: "+92 (300) 234-5678",
    grade: "Grade 10 (Matric)",
    section: "A (Science)",
    guardianName: "Tariq Khan",
    guardianPhone: "+92 (300) 987-6541",
    address: "Main Bazar, Permoli, District Swabi, KPK",
    admissionDate: "2024-08-15",
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80",
    bloodGroup: "O+",
    dob: "2010-04-12",
    status: "active",
    totalFee: 24000,
    paidFee: 24000,
    remainingFee: 0,
    dueDate: "2026-10-15",
    feeStatus: "paid",
    totalMarks: 1100,
    obtainedMarks: 995,
    percentage: 90.5,
    gradePerformance: "A+ (Distinction)",
    examTerm: "BISE Mardan Board Prep",
    attendancePercentage: 97,
  },
  {
    id: "stu-2",
    rollNo: "IPS-2026-002",
    name: "Ayesha Bibi",
    email: "ayesha.bibi@example.com",
    phone: "+92 (312) 345-6789",
    grade: "Grade 9 (Science)",
    section: "B",
    guardianName: "Muhammad Irfan",
    guardianPhone: "+92 (312) 876-5432",
    address: "Village Permoli, Swabi",
    admissionDate: "2023-08-10",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80",
    bloodGroup: "A+",
    dob: "2011-07-22",
    status: "active",
    totalFee: 22000,
    paidFee: 14000,
    remainingFee: 8000,
    dueDate: "2026-09-30",
    feeStatus: "partial",
    totalMarks: 1100,
    obtainedMarks: 940,
    percentage: 85.5,
    gradePerformance: "A (Excellent)",
    examTerm: "BISE Mardan Board Prep",
    attendancePercentage: 95,
  },
  {
    id: "stu-3",
    rollNo: "IPS-2026-003",
    name: "Bilal Ahmad",
    email: "bilal.ahmad@example.com",
    phone: "+92 (333) 456-7890",
    grade: "Grade 8 (Middle)",
    section: "A",
    guardianName: "Ahmad Ali",
    guardianPhone: "+92 (333) 765-4321",
    address: "Near Jamia Masjid, Permoli",
    admissionDate: "2025-08-12",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    bloodGroup: "B+",
    dob: "2012-11-05",
    status: "active",
    totalFee: 18000,
    paidFee: 6000,
    remainingFee: 12000,
    dueDate: "2026-08-15",
    feeStatus: "overdue",
    totalMarks: 500,
    obtainedMarks: 415,
    percentage: 83.0,
    gradePerformance: "A (Excellent)",
    examTerm: "Annual Term Assessment",
    attendancePercentage: 92,
  },
  {
    id: "stu-4",
    rollNo: "IPS-2026-004",
    name: "Fatima Noor",
    email: "fatima.noor@example.com",
    phone: "+92 (345) 567-8901",
    grade: "Grade 10 (Matric)",
    section: "A (Science)",
    guardianName: "Noor Muhammad",
    guardianPhone: "+92 (345) 654-3210",
    address: "College Road, Permoli",
    admissionDate: "2022-08-20",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80",
    bloodGroup: "AB+",
    dob: "2009-03-18",
    status: "active",
    totalFee: 24000,
    paidFee: 24000,
    remainingFee: 0,
    dueDate: "2026-11-01",
    feeStatus: "paid",
    totalMarks: 1100,
    obtainedMarks: 1020,
    percentage: 92.7,
    gradePerformance: "A+ (1st Position)",
    examTerm: "BISE Mardan Board Exam",
    attendancePercentage: 99,
  },
  {
    id: "stu-5",
    rollNo: "IPS-2026-005",
    name: "Usman Ghani",
    email: "usman.g@example.com",
    phone: "+92 (301) 678-9012",
    grade: "Grade 7",
    section: "C",
    guardianName: "Ghani Ur Rehman",
    guardianPhone: "+92 (301) 543-2109",
    address: "Permoli Bypass, Swabi",
    admissionDate: "2025-08-14",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    bloodGroup: "O-",
    dob: "2013-09-30",
    status: "active",
    totalFee: 16000,
    paidFee: 8000,
    remainingFee: 8000,
    dueDate: "2026-10-20",
    feeStatus: "partial",
    totalMarks: 500,
    obtainedMarks: 380,
    percentage: 76.0,
    gradePerformance: "B (Good)",
    examTerm: "Mid-Term Examination",
    attendancePercentage: 90,
  },
  {
    id: "stu-6",
    rollNo: "IPS-2026-006",
    name: "Zainab Tariq",
    email: "zainab.t@example.com",
    phone: "+92 (315) 789-0123",
    grade: "Grade 5 (Primary)",
    section: "A",
    guardianName: "Tariq Mehmood",
    guardianPhone: "+92 (315) 432-1098",
    address: "Hospital Road, Permoli",
    admissionDate: "2024-08-15",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    bloodGroup: "A-",
    dob: "2015-01-14",
    status: "active",
    totalFee: 14000,
    paidFee: 14000,
    remainingFee: 0,
    dueDate: "2026-10-15",
    feeStatus: "paid",
    totalMarks: 500,
    obtainedMarks: 465,
    percentage: 93.0,
    gradePerformance: "A+ (Outstanding)",
    examTerm: "Final Primary Assessment",
    attendancePercentage: 98,
  }
];

export const DEFAULT_PAYMENTS: FeePayment[] = [
  {
    id: "pay-1",
    studentId: "stu-1",
    studentName: "Muhammad Hamza Khan",
    rollNo: "IPS-2026-001",
    grade: "Grade 10 (Matric)",
    amount: 24000,
    paymentMethod: "bank_transfer",
    date: "2026-08-10",
    receiptNo: "REC-2026-1001",
    notes: "Full Annual Tuition and Science Lab Fee clearance",
    academicYear: "2026-2027",
  },
  {
    id: "pay-2",
    studentId: "stu-2",
    studentName: "Ayesha Bibi",
    rollNo: "IPS-2026-002",
    grade: "Grade 9 (Science)",
    amount: 14000,
    paymentMethod: "cash",
    date: "2026-08-14",
    receiptNo: "REC-2026-1002",
    notes: "1st Installment Paid at Accounts Office",
    academicYear: "2026-2027",
  },
  {
    id: "pay-3",
    studentId: "stu-3",
    studentName: "Bilal Ahmad",
    rollNo: "IPS-2026-003",
    grade: "Grade 8 (Middle)",
    amount: 6000,
    paymentMethod: "cash",
    date: "2026-07-28",
    receiptNo: "REC-2026-1003",
    notes: "Admission registration deposit",
    academicYear: "2026-2027",
  },
  {
    id: "pay-4",
    studentId: "stu-4",
    studentName: "Fatima Noor",
    rollNo: "IPS-2026-004",
    grade: "Grade 10 (Matric)",
    amount: 24000,
    paymentMethod: "online",
    date: "2026-08-01",
    receiptNo: "REC-2026-1004",
    notes: "Senior Year Full Term Fee Paid Online",
    academicYear: "2026-2027",
  },
  {
    id: "pay-5",
    studentId: "stu-5",
    studentName: "Usman Ghani",
    rollNo: "IPS-2026-005",
    grade: "Grade 7",
    amount: 8000,
    paymentMethod: "cash",
    date: "2026-08-18",
    receiptNo: "REC-2026-1005",
    notes: "Semester 1 payment",
    academicYear: "2026-2027",
  },
  {
    id: "pay-6",
    studentId: "stu-6",
    studentName: "Zainab Tariq",
    rollNo: "IPS-2026-006",
    grade: "Grade 5 (Primary)",
    amount: 14000,
    paymentMethod: "bank_transfer",
    date: "2026-08-05",
    receiptNo: "REC-2026-1006",
    notes: "Full Tuition Fee Paid",
    academicYear: "2026-2027",
  }
];

export const DEFAULT_GALLERY: GalleryItem[] = [
  {
    id: "gal-mural",
    title: "Official Landmark Campus Mural & Main Gate",
    category: "campus",
    imageUrl: "/images/iqra-school-event.jpg",
    description: "The iconic hand-painted campus wall mural and main entrance archway at Iqra Public School Permoli.",
    uploadDate: "2026-09-22",
    featured: true,
  },
  {
    id: "gal-hero",
    title: "Faculty & Senior Students Annual Gathering",
    category: "events",
    imageUrl: "/images/iqra-hero.jpg",
    description: "Honorable Principal Akhter Munir, esteemed faculty members, and senior students at the Permoli campus.",
    uploadDate: "2026-09-22",
    featured: true,
  },
  {
    id: "gal-preschool",
    title: "Pre-School Activity & Phonics Learning",
    category: "academics",
    imageUrl: "/images/iqra-preschool.jpg",
    description: "Young Montessori and Kindergarten learners engaging in cognitive building blocks and interactive phonics in Permoli.",
    uploadDate: "2026-09-22",
    featured: true,
  },
  {
    id: "gal-primary",
    title: "Primary School Interactive Classroom Session",
    category: "academics",
    imageUrl: "/images/iqra-primary.jpg",
    description: "Primary section students engaged in mathematics problem solving, English grammar, and interactive Urdu comprehension.",
    uploadDate: "2026-09-22",
    featured: true,
  },
  {
    id: "gal-middle",
    title: "Middle School Practical Science & IT Project Work",
    category: "academics",
    imageUrl: "/images/iqra-middle.jpg",
    description: "Hands-on biological models, digital research on laptops, and collaborative science projects guided by senior faculty.",
    uploadDate: "2026-09-22",
    featured: true,
  },
  {
    id: "gal-matric",
    title: "BISE Mardan Board Prep & Reference Library",
    category: "academics",
    imageUrl: "/images/iqra-matric.jpg",
    description: "Senior secondary matric students conducting group study and exam preparation in the campus reference library.",
    uploadDate: "2026-09-22",
    featured: true,
  },
  {
    id: "gal-mural-art",
    title: "Landmark Campus Art & Calligraphy Permoli",
    category: "campus",
    imageUrl: "/images/iqra-school-mural.png",
    description: "Artistic campus wall painting showcasing motivational educational quotes and school heritage in Permoli.",
    uploadDate: "2026-09-20",
    featured: true,
  },
  {
    id: "gal-principal",
    title: "Principal Akhter Munir Academic Assembly Address",
    category: "events",
    imageUrl: "/images/principal-akhter-munir.png",
    description: "Principal Akhter Munir addressing the student assembly on academic discipline, moral values, and future vision.",
    uploadDate: "2026-09-18",
    featured: true,
  },
  {
    id: "gal-physics-lab",
    title: "Science & Physics Experimentation Lab",
    category: "academics",
    imageUrl: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=800&auto=format&fit=crop&q=80",
    description: "Matric and middle school students conducting practical science and optics experiments in modern laboratory.",
    uploadDate: "2026-09-15",
    featured: true,
  },
  {
    id: "gal-cricket",
    title: "Annual Sports Day & Cricket Championship",
    category: "sports",
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop&q=80",
    description: "Students showcasing athletic skills, cricket tournament teamwork, and school spirit on our sports ground.",
    uploadDate: "2026-09-10",
    featured: true,
  },
  {
    id: "gal-comp-lab",
    title: "Modern Computer Lab & Digital Coding Class",
    category: "academics",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80",
    description: "High-speed modern computers equipped for student programming, IT skills, and online educational research.",
    uploadDate: "2026-09-08",
    featured: true,
  },
  {
    id: "gal-qirat",
    title: "Annual Qirat, Naat & Speech Competition",
    category: "arts",
    imageUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80",
    description: "Celebrating student eloquence, Islamic knowledge, and public speaking excellence in the grand auditorium.",
    uploadDate: "2026-09-05",
    featured: true,
  },
  {
    id: "gal-prizes",
    title: "Matriculation High Achievers & Prize Distribution",
    category: "events",
    imageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80",
    description: "Honoring top BISE board position holders and meritorious scholars of Permoli with medals and shields.",
    uploadDate: "2026-09-02",
    featured: true,
  },
  {
    id: "gal-football",
    title: "Inter-House Football & Athletics Tournament",
    category: "sports",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80",
    description: "Exciting inter-house football tournament matches held on the lush green campus sports field.",
    uploadDate: "2026-08-28",
    featured: false,
  },
];

export const DEFAULT_CERTIFICATES: Certificate[] = [
  {
    id: "cert-1",
    studentId: "stu-4",
    studentName: "Fatima Noor",
    rollNo: "IPS-2026-004",
    grade: "Grade 10 (Matric)",
    title: "Certificate of Academic Excellence",
    type: "academic_excellence",
    issueDate: "2026-06-25",
    description: "Awarded for exceptional academic standing and securing 1st Position in Science with A+ Grade at Iqra Public School Permoli.",
    certificateNo: "IPS-PERMOLI-2026-001",
    principalName: "Akhter Munir",
    sealColor: "#ca8a04",
    honors: "1st Position with High Distinction (A+ Grade)",
  },
  {
    id: "cert-2",
    studentId: "stu-1",
    studentName: "Muhammad Hamza Khan",
    rollNo: "IPS-2026-001",
    grade: "Grade 10 (Matric)",
    title: "Sports Leadership Award",
    type: "sports",
    issueDate: "2026-05-30",
    description: "In recognition of outstanding athletic leadership, discipline, and leading the school cricket team to victory in the Permoli Inter-School Cup.",
    certificateNo: "IPS-PERMOLI-2026-002",
    principalName: "Akhter Munir",
    sealColor: "#026ec9",
    honors: "Captain of Varsity Team & Best All-Rounder",
  }
];

export const DEFAULT_NOTICES: Notice[] = [
  {
    id: "not-1",
    title: "Admissions Open for Session 2026-2027 (Nursery to Class 10)",
    content: "Admissions are now open at Iqra Public School Permoli. Limited seats available in Science & Computer groups. Concession available for orphan and needy students.",
    date: "2026-09-10",
    category: "admission",
    priority: "urgent",
    active: true,
  },
  {
    id: "not-2",
    title: "BISE Board Assessment & Mid-Term Date Sheet",
    content: "Mid-term examinations for Classes 1 to 10 will begin next month. Detailed syllabi and date sheets have been distributed in classrooms.",
    date: "2026-09-15",
    category: "exam",
    priority: "high",
    active: true,
  },
  {
    id: "not-3",
    title: "Annual Sports Gala & Speech Competition",
    content: "Annual sports week and Inter-House Qirat & Naat competition scheduled for next week. All parents are warmly invited to attend.",
    date: "2026-09-18",
    category: "event",
    priority: "normal",
    active: true,
  }
];

export const DEFAULT_INQUIRIES: Inquiry[] = [
  {
    id: "inq-1",
    fullName: "Muhammad Tariq Khan",
    email: "tariq.k@example.com",
    phone: "+92 (300) 555-1122",
    gradeApplying: "Grade 9 (Science)",
    message: "Seeking admission for my son in Class 9 Science group. Would like to inquire about van transport routes in Permoli.",
    date: "2026-09-19",
    status: "new",
  },
  {
    id: "inq-2",
    fullName: "Sajjad Ahmad",
    email: "sajjad.a@example.com",
    phone: "+92 (312) 666-3344",
    gradeApplying: "Nursery / KG",
    message: "Looking for nursery admission and early childhood facilities for my daughter.",
    date: "2026-09-18",
    status: "contacted",
  }
];
